- name: make temp directory for SSH public keys
  file: path=/tmp/public_keys/ state=directory

- name: copy downloaded SSH public keys to CA for signing
  copy: src={{ ansible_temp_directory }}/keys/{{ item.key }}.pub dest=/tmp/public_keys/
  with_dict: "{{ users }}"

- name: create signed certificates with appropriate principals
  command: ssh-keygen -s /etc/ssh/CA/CA -I {{ item.key }} -n {{ item.value }} -V +1d /tmp/public_keys/{{ item.key }}.pub
  with_dict:
    "{{ users }}"

- name: download signed certificates
  fetch: src=/tmp/public_keys/{{ item.key }}-cert.pub dest={{ ansible_temp_directory }}/certs/{{ item.key }}-cert.pub flat=yes
  with_dict:
    "{{ users }}"

- name: delete temporary public key directory
  file: path=/tmp/public_keys/ state=absent
